#!/usr/bin/env python

import os
import sys
import subprocess
from git import Git

# Rider powerclass
class Rider:

  # Initialize a directory for Rider
  def rider_init(self):
    print "Initalizing Rider"

    if os.path.exists('.rider'):
      sys.exit('Rider has already been initialized!')

    # Setup rider lib
    if not os.path.exists('rider'):
      Git().clone("https://github.com/HackRider/Rider-lib.git")
      os.rename('Rider-lib', 'rider')

    # Setup the directories the user code will exist
    if not os.path.exists('controllers'):
      os.makedirs('controllers')
    if not os.path.exists('views'):
      os.makedirs('views')
    if not os.path.exists('build'):
      os.makedirs('build')
    if not os.path.exists('public/js'):
      os.makedirs('public/js')
    if not os.path.exists('public/css'):
      os.makedirs('public/css')

    # Mark the directory as created by Rider
    if not os.path.exists('.rider'):
      file('.rider', 'w')

    print "Finished Initalizing Rider"

  def verify_rider_initalized(self):
    if not os.path.exists('.rider'):
      sys.exit("Not a valid Rider project. To initalize rider, "
               "run \"rider init\"")

  # Create a controller
  def rider_controller(self):
    controller = raw_input('Enter desired controller name: ')
    if not os.path.exists('controllers/' + controller):
      file('controllers/' + controller, 'w')
    else:
      sys.exit('Controller ' + controller + ' already exists')
    path = os.path.exists('Enter desired endpoint: ')

  def rider_create_maps(self):
    path = os.path.realpath(__file__).rpartition('/')[0]
    subprocess.call(['hhvm', path + '/AutoloadMapGenerator.php'])
    subprocess.call(['hhvm', path + '/URIMapGenerator.php'])

if (len(sys.argv) < 2):
  sys.exit('Invalid usage')

command = sys.argv[1].lower()
rider = Rider()
if command == 'init':
  rider.rider_init()
  sys.exit()

rider.verify_rider_initalized() 
if command == 'controller':
  rider.rider_controller()
elif command == 'build':
  rider.rider_create_maps()
